[General]
autoConfig=true
autoConfigPrompted=true
autoHide=false
autoStart=false
cryptoEnabled=true
elevateMode=false
elevateModeEnum=0
groupClientChecked=false
groupServerChecked=true
interface=
language=en
logFilename=/var/log/barrier.log
logLevel=3
logToFile=false
minimizeToTray=false
port=24800
requireClientCertificate=false
screenName=Iphonel
startedBefore=true
wizardLastRun=9
